### ISSUE TITLE
Doesn't copy to clipboard on android

### ISSUE THREAD

**Issue by flip111** [charlesbrandt/copy_all_tabs#11]
Extension shows up in the menu. The page opens and shows a button "copy tabs" but it doesn't replace the text on the clipboard.

**Comment by langfingaz** [comment]
I can confirm, that on Fennec (version 68.10.1) on Android one can install and launch the extension but as stated above, the "copy tabs" button has no effect.

I'm not sure it is a goal of this project to also work on Android (Firefox Mobile) but I would be a great feature!
One could copy all open tabs from android, send them in some private way to ones pc and open them up again. Without relying on any synchronisation service.

**Comment by charlesbrandt** [comment]
I have removed the flag that this extension works with Firefox on Android. I would love to find a way to make it work on Android, but I don't think the Android version of the browser has the same API into the system clipboard that the desktop versions have. 

One work around I've considered is showing the list of tab urls in a text area that then could be manually copied into the clipboard. 

However, newer versions of Firefox for Android (e.g. 83+) have a much smaller list of add-ons that are available. It seems the process for being part of that list has changed. 

One work around is to synchronize the tabs to a desktop browser with Firefox Sync, and then use Copy All Tabs on the desktop to get the list.
