### ISSUE TITLE
Default Action

### ISSUE THREAD

**Issue by n0rbertt** [charlesbrandt/copy_all_tabs#12]
First of let me say thanks for creating a plugin that can both copy and paste tab urls , very useful :) . I could've sworn there was a way to set a default action for the button so it only took 1 click to copy all urls ... or was that a different plugin ?

**Comment by charlesbrandt** [comment]
Thank you for the feedback. I'm glad you find the extension useful. 

I agree that one click would be better. However, I can't think of a way to choose multiple actions (copy vs paste) and also have a default action with only one button.
