### ISSUE TITLE
Multiple Instances of Item Values

### ISSUE THREAD

**Issue by manngo** [charlesbrandt/copy_all_tabs#17]
I have an output format in the following form:

```
-	${tab.title}
	[${tab.url}](${tab.url})
```

The problem is that the term `tab.url` is replaced only once.

I think that would be easily fixed in the `tabs.js` file by replacing `.replace()` with `.replaceAll()`:

```js
function convertTabToListItem(tab, format = "${tab.url}\r\n${tab.title}\r\n") {
  format = format.replaceAll("${tab.url}", tab.url);
  const tabListItem = format.replaceAll("${tab.title}", tab.title);
  return tabListItem;
}
```

Would it be possible to implement this?

**Comment by charlesbrandt** [comment]
Thank you for this issue, @manngo. I have applied the fix in version 0.0.10
