### ISSUE TITLE
Does not work in Private window

### ISSUE THREAD

**Issue by GronbergInfo** [charlesbrandt/copy_all_tabs#2]
When i try to paste tabs into a private window, nothing happens

**Comment by charlesbrandt** [comment]
I've noticed an issue where paste tabs will not work with any of the default Firefox tabs, including a new tab ('about:newtab'). This is a bug on all windows, not just private windows. If you navigate to another site (e.g. google.com) in your private window, does Paste tabs work then? 

Thanks for the feedback.

**Comment by charlesbrandt** [comment]
This should be fixed in version 0.0.8.
