### ISSUE TITLE
Insert line break after URL possible?

### ISSUE THREAD

**Issue by chad-ld** [charlesbrandt/copy_all_tabs#21]
@charlesbrandt Hi, currently my settings for the plugin looks like this:
${tab.title}
${tab.url}

This works good, shows the title, does a line break, shows the URL, but then immediately lists the next tab title on the same line as the previous URL, without going down to a new line first. Is there a token or character I can insert to make sure each title and URL is on its own line?

**Comment by pzhlkj6612** [comment]
Hi. I use the following output format to insert a line break after each group:

```
1   ${tab.url}
2   ${tab.title}
3   
4   
```

These numbers are line numbers. The 3rd and 4th lines are empty lines.

**Comment by chad-ld** [comment]
ah, perfect! I had tried it with one blank space, but didn't realize I needed two. Thanks so much (and thanks for the plugin!)

**Comment by chad-ld** [comment]
problem solved as shown above
