### ISSUE TITLE
Can't copy URLs only

### ISSUE THREAD

**Issue by ghost** [charlesbrandt/copy_all_tabs#4]
When switching on FF, this was the closest extension to _[Copy All Urls](https://chrome.google.com/webstore/detail/copy-all-urls/djdmadneanknadilpjiknlnanaolmbfk)_ that I could find and I like it. However, I personally have no interest in copying anything else but URLs and it would be great to be able to copy URLs only, without page titles.

**Comment by charlesbrandt** [comment]
Version 0.0.8 adds an options / settings page that you can choose to exclude titles. [(Thanks refset for adding this feature)](https://github.com/charlesbrandt/copy_all_tabs/commit/076fbf16c8aa476195a3cffa640d903b57952c06)
