### ISSUE TITLE
doesn't work - FF 56.0.2 (64 bit)

### ISSUE THREAD

**Issue by crystal90** [charlesbrandt/copy_all_tabs#5]
I really wanted this work but it doesn't. When I click on 'copy tabs' nothing happens, nothing get copied to the clipboard.

I'm on an older version of FF for a reason and I don't want to update at this time.

Can this be fixed?

Thanks,

**Comment by rensbaardman** [comment]
I have the same problem with the most recent version (59.0.2).

Moving tabs *does* work.

**Comment by charlesbrandt** [comment]
For older versions of the webextension (pre 0.0.8) I would see this behavior on new (empty) tabs or on firefox specific tabs (e.g. about:debugging). Using it on a tab with a page loaded (e.g. google.com) would allow the add-on to work. 

The new version (0.0.8) addresses that issue and should work on any tab. 

However, I have noticed an issue on Linux versions of Firefox where Copy Tabs does not work. I'm still looking in to that one. Please let me know if you're still seeing the original problem with the new version.

**Comment by charlesbrandt** [comment]
The extension seems to work as expected on Linux now with version 64.0 (Firefox) and 0.0.8 of Copy All Tabs. It's also been working on Mac and Windows versions of Firefox for some time. For older versions of Firefox you may want to try earlier versions of the extension: 
https://addons.mozilla.org/en-US/firefox/addon/copy-all-tabs/versions/

**Comment by grahamperrin** [comment]
@charlesbrandt maybe add a `strict_min_version` to the extension? And update the page at AMO; so that users don't inadvertently install an incompatible version. 

Thanks

(Waterfox Classic 56.2.13 here.)
