### ISSUE TITLE
Why does it need permission to 'Access your data for all websites'?

### ISSUE THREAD

**Issue by rensbaardman** [charlesbrandt/copy_all_tabs#6]
When installing, it says the add-on needs permission to 'Access your data for all websites'. Is that really necessary? It seems to me that the permission to 'Access browser tabs' should be enough (but I am not a developer of add-ons, so I don't know the details).

I am a little wary to give over so much control to an add-on, even if it's open source (but thanks for being open source in the first place!). Even when it's possible to inspect the code on GitHub, you can never be sure that that's the code that get's installed. (and yes, you could also inspect the installed code, but it can be quite easy to hide something malicious into something that looks OK)

**Comment by rensbaardman** [comment]
For comparison, the similar add-on [Copy All Tab Urls WE](https://addons.mozilla.org/en-US/firefox/addon/copy-all-tab-urls-we/?src=search) doesn't need this permission.

**Comment by charlesbrandt** [comment]
Thanks for the question. I configured that permission when I was trying to figure out how to get the webextension to work regardless of what type of tab was open (e.g. new tab). The permission did not help with that issue, so I've removed it in version 0.0.8. Good call!
