### ISSUE TITLE
Changing custom separator field breaks new lines in list of tabs

### ISSUE THREAD

**Issue by plaindan** [charlesbrandt/copy_all_tabs#8]
I love your add-on (used CopyAllURLs until it was yanked). I liked that add-ons ability to add a blank line between tabs in the dump to make it easier to scan.

Thinking your add-on might offer the same functionality, I messed with the textbox on the management page, substituting "new line" for the default "undefined". To my horror the dump was all run-on, with no line breaks at all. Thinking to undo the mess I created, I re-entered "undefined" in the text box but it is still messed up. What to do? Is there the functionality I am looking for? (blank line between each tab in the dump). Thank you!

**Comment by pmorch** [comment]
I ran into this too. Just removing the entire contents of the box so it is empty reverts to the original `undefined` behavior. (So does removing the addon, restarting the browser, and re-installing it).

I guess everybody wants something different as far as formats go, but an initial value of `undefined` that doesn't do the same as the string (also) `"undefined"` is not intuitive.

**Comment by charlesbrandt** [comment]
The new version of Copy All Tabs (0.0.9) provides a way for users to specify the desired output format as a string in the settings. I'm hopeful that it addresses this issue with the `undefined` separator in the previous version. 

Apologies for the delay in the fix. Thank you for creating the issue, and please let me know if you see any other issues with this feature.
