### ISSUE TITLE
Support custom formats

### ISSUE THREAD

**Issue by pmorch** [charlesbrandt/copy_all_tabs#9]
I guess everybody wants a different output format. Being a programmer, I can quickly write a a little script to create custom formats from the default two-lines-per-tab format, but even better would be something like [evilnickname/link-text-location-copier: Firefox web extension that lets you copy link text and location.](https://github.com/evilnickname/link-text-location-copier) does:

![image](https://user-images.githubusercontent.com/159292/49518016-e0362980-f89d-11e8-93fd-b57ecd79c16a.png)

and configuration:
![image](https://user-images.githubusercontent.com/159292/49518040-ef1cdc00-f89d-11e8-8d8a-812450b6fd58.png)

Since these two extensions are both open-source it would be wonderful if they could share a common library for this functionality. But otherwise some common formats would be nice:

* Text: `%Title - %URL`
* HTML: `<a href="%URL">%Title</a>`
* Rich text links

**Comment by charlesbrandt** [comment]
Thank you for this great suggestion! The new version of Copy All Tabs (0.0.9) provides a way for users to specify the desired output format as a string in the settings. 

It's not as full featured as the example you gave, but I would be interested to hear if it meets your needs for customizing the format.
